name: Terraform Security Scans

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      # ---------- tfsec ----------
      - name: Run tfsec (SARIF)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          args: --format sarif --out tfsec.sarif .
        continue-on-error: true

      - name: Verify tfsec.sarif
        run: ls -lh tfsec.sarif || echo "tfsec.sarif not found"

      - name: Upload tfsec SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
          category: tfsec

      # ---------- Checkov ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov (SARIF)
        run: checkov -d . -o sarif > checkov.sarif
        continue-on-error: true

      - name: Verify checkov.sarif
        run: ls -lh checkov.sarif || echo "checkov.sarif not found"

      - name: Upload Checkov SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif
          category: checkov
